# CAT: Create 2 ConfigMaps then sleep 1s.
name: cat-create-two-configmaps
namespace:
  number: 1
tuningSets:
- name: default
  globalQPSLoad:
    qps: 1
    burst: 2
steps:
- name: Create 2 ConfigMaps
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 2
    tuningSet: default
    objectBundle:
    - basename: cat-cm-multi
      objectTemplatePath: configmap.yaml
- name: Sleep 1s
  measurements:
  - Identifier: Sleep1s
    Method: Sleep
    Params:
      duration: 1s
